# Generated by Django 4.0.5 on 2022-07-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlanc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='telefono',
            new_name='edad',
        ),
    ]
